### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kgraefe** [Agalin/pidgin_macos_integration#8]
I am no expert, but I think your licensing is not compatible with Pidgin/libpurple.

From what I understand, GPL code can call BSD code, but not the other way around. Therefore as Pidgin and libpurple are under GPL, plugins must be GPL as well.

**Comment by Agalin** [comment]
If I understand licenses correctly, GPL code can be used with any GPL-ompatible license. And GNU [lists](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) BSD (edit. 2: BSD 2-clause is listed as FreeBSD) as GPL-compatible. But I'm not a lawyer and if you have any sources that explain this, then I'll change license.

Edit. Pidgin itself [says](https://developer.pidgin.im/wiki/Scripting%20and%20Plugins#Aretherelicensingrestrictionsonplugins) that plugin license should be GPL-compliant, not exactly GPL.

**Comment by kgraefe** [comment]
According to GNU [compatible](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean) means that  `you can combine code released under the other license with code released under the GNU GPL in one larger program [...] provided the combination is released under the same GNU GPL version.`

**Comment by Agalin** [comment]
And BSD allows that. It's actually MORE open than GNU/GPL.
Combination in this case is Pidgin bundled with plugin - and BSD licensed plugin can be freely merged into GPL code.

**Comment by Agalin** [comment]
I think that this [FAQ entry](https://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense) describes situation best. Plugin is an additional module and 2-clause BSD is compliant as more lax so it can be used there.

**Comment by kgraefe** [comment]
Sorry for wasting your time then ❤️

**Comment by Agalin** [comment]
No problem, I'm never sure about those. THat's one of the reasons I'm not a fan of GPL - license cooperation.
